### ISSUE TITLE
Record error handling example

### ISSUE THREAD

**Issue by d9k** [givo/lib-kurento#4]
Thanks for sharing awesome library!
I suggest adding these lines to the `Recording Example` in `README.md`:

```
recorderEndpoint.endpoint.addListener('Error', (err) => {
  console.log('recorderEndpoint.endpoint error', err);
 })
```

It greatly helps to debug recording problems.

**Comment by givo** [comment]
Hi,

Thank you very much for using my library :)

Sounds good, I'll add your suggestion.

**Comment by d9k** [comment]
@givo,

Sorry, you closed this issue but did not made any new commits :sweat_smile: 

Just a remind, maybe you forgot to push)

**Comment by givo** [comment]
Hi,

Sorry that it took so long, I'm very busy lately, but there you go!

Thank you again :)
