### ISSUE TITLE
WebSocket.on is not defined

### ISSUE THREAD

**Issue by jmezzera** [givo/lib-kurento#8]
Hi,
In both examples of the README, there's a call to `socket.on` where `socket` is of type `WebSocket`.
However, `WebSocket` does not have any member `on`. How do I proceed? 

I'm compiling to es5 and have the libraries for es2019 and dom in my `tsconfig.json`

Thanks in advance.

**Comment by givo** [comment]
It's not a working example, I preset a theoretical signaling mechanism. I can recommend using [socketio](https://socket.io/) or if you can use an HTTP signaling mechanism and make you application stateless as much as you can!
